return {
	StartingHeroId = "Knight",
	HeroOrder = {"Knight", "Archer", "Mage"},
	Knight = {
		HeroId = "Knight",
		OwnedByDefault = true,
		UnlockCost = 0,
		RigType = "Knight",
		CombatStyle = "Melee",
		Name = "Knight",
		BaseDamage = 20,
		DamageGrowth = 1.08,
		BaseLevelCost = 10,
		LevelCostGrowth = 1.12,
		MaxLevel = 200,
		Milestones = {
			{
				Id = "SharpenedBlade", Level = 10, Name = "Sharpened Blade",
				Description = "This hero's damage x2", Cost = 100,
				Effect = {Type = "HeroDamageMultiplier", Value = 2},
			},
			{
				Id = "KnightTraining", Level = 25, Name = "Knight Training",
				Description = "This hero's damage x2", Cost = 1000,
				Effect = {Type = "HeroDamageMultiplier", Value = 2},
			},
			{
				Id = "TreasureHunter", Level = 50, Name = "Treasure Hunter",
				Description = "Your gold earned x1.25", Cost = 10000,
				Effect = {Type = "GoldMultiplier", Value = 1.25},
			},
			{
				Id = "SwordMastery", Level = 100, Name = "Sword Mastery",
				Description = "This hero's damage x5", Cost = 1000000,
				Effect = {Type = "HeroDamageMultiplier", Value = 5},
			},
			{
				Id = "BattleInspiration", Level = 150, Name = "Battle Inspiration",
				Description = "All your heroes' damage x1.25", Cost = 100000000,
				Effect = {Type = "GlobalHeroDamageMultiplier", Value = 1.25},
			},
			{
				Id = "LegendaryKnight", Level = 200, Name = "Legendary Knight",
				Description = "This hero's damage x10", Cost = 10000000000,
				Effect = {Type = "HeroDamageMultiplier", Value = 10},
			},
		},
		-- Minimum time between attack starts, including animation and cooldown.
		AttackInterval = 1.3,
		SlotOffset = Vector3.new(0, -1.6, 5.3),
		Animation = {
			WindupDuration = 0.28,
			SwingDuration = 0.16,
			FollowThroughDuration = 0.14,
			RecoveryDuration = 0.32,
			IdleAngle = 65,
			WindupAngle = 165,
			ImpactAngle = 100,
			FollowThroughAngle = 65,
		},
		Visual = {
			ArmorColor = Color3.fromRGB(150, 165, 185),
			DarkArmorColor = Color3.fromRGB(65, 75, 95),
			ClothColor = Color3.fromRGB(150, 35, 45),
			BladeColor = Color3.fromRGB(220, 235, 245),
			GoldColor = Color3.fromRGB(205, 165, 65),
			GripColor = Color3.fromRGB(75, 45, 30),
			Scale = 1,
		},
	},
	Archer = {
		HeroId = "Archer", Name = "Archer", OwnedByDefault = false,
		UnlockCost = 100, RigType = "Ranged", CombatStyle = "Bow",
		BaseDamage = 8, DamageGrowth = 1.08,
		BaseLevelCost = 15, LevelCostGrowth = 1.12, MaxLevel = 200,
		AttackInterval = 0.7,
		SlotOffset = Vector3.new(5, -1.6, 9),
		Animation = {
			WindupDuration = 0.12, SwingDuration = 0.22,
			FollowThroughDuration = 0.08, RecoveryDuration = 0.13,
			IdleAngle = 65, WindupAngle = 100, ImpactAngle = 75, FollowThroughAngle = 65,
		},
		Visual = {
			ClothColor = Color3.fromRGB(45, 115, 60),
			TrimColor = Color3.fromRGB(100, 65, 35),
			SkinColor = Color3.fromRGB(220, 175, 130),
			ProjectileColor = Color3.fromRGB(220, 185, 125),
			ProjectileSize = Vector3.new(0.12, 0.12, 1.8),
			Scale = 1,
		},
		Milestones = {
			{Id = "KeenArrows", Level = 10, Name = "Keen Arrows",
				Description = "Archer damage x2", Cost = 150,
				Effect = {Type = "HeroDamageMultiplier", Value = 2}},
			{Id = "QuickDraw", Level = 25, Name = "Quick Draw",
				Description = "Archer attack speed x1.25", Cost = 1500,
				Effect = {Type = "AttackSpeedMultiplier", Value = 1.25}},
			{Id = "RallyingVolley", Level = 50, Name = "Rallying Volley",
				Description = "All your heroes' damage x1.20", Cost = 15000,
				Effect = {Type = "GlobalHeroDamageMultiplier", Value = 1.2}},
			{Id = "Deadeye", Level = 100, Name = "Deadeye",
				Description = "Archer damage x5", Cost = 1500000,
				Effect = {Type = "HeroDamageMultiplier", Value = 5}},
			{Id = "GiantSlayer", Level = 150, Name = "Giant Slayer",
				Description = "Archer boss damage x2", Cost = 150000000,
				Effect = {Type = "BossDamageMultiplier", Value = 2}},
			{Id = "LegendaryArcher", Level = 200, Name = "Legendary Archer",
				Description = "Archer damage x10", Cost = 15000000000,
				Effect = {Type = "HeroDamageMultiplier", Value = 10}},
		},
	},
	Mage = {
		HeroId = "Mage", Name = "Mage", OwnedByDefault = false,
		UnlockCost = 1000, RigType = "Ranged", CombatStyle = "Magic",
		BaseDamage = 55, DamageGrowth = 1.09,
		BaseLevelCost = 40, LevelCostGrowth = 1.12, MaxLevel = 200,
		AttackInterval = 2.4,
		SlotOffset = Vector3.new(-5, -1.6, 9),
		Animation = {
			WindupDuration = 0.5, SwingDuration = 0.45,
			FollowThroughDuration = 0.15, RecoveryDuration = 0.35,
			IdleAngle = 65, WindupAngle = 135, ImpactAngle = 85, FollowThroughAngle = 65,
		},
		Visual = {
			ClothColor = Color3.fromRGB(100, 60, 155),
			TrimColor = Color3.fromRGB(190, 155, 65),
			SkinColor = Color3.fromRGB(220, 175, 130),
			ProjectileColor = Color3.fromRGB(140, 180, 255),
			ProjectileSize = Vector3.new(0.65, 0.65, 0.65),
			Scale = 1,
		},
		Milestones = {
			{Id = "ArcaneFocus", Level = 10, Name = "Arcane Focus",
				Description = "Mage damage x2", Cost = 300,
				Effect = {Type = "HeroDamageMultiplier", Value = 2}},
			{Id = "Spellcraft", Level = 25, Name = "Spellcraft",
				Description = "Mage damage x2", Cost = 3000,
				Effect = {Type = "HeroDamageMultiplier", Value = 2}},
			{Id = "EnchantedBlade", Level = 50, Name = "Enchanted Blade",
				Description = "Knight damage x1.5", Cost = 30000,
				Effect = {Type = "SpecificHeroDamageMultiplier", TargetHeroId = "Knight", Value = 1.5}},
			{Id = "Archmage", Level = 100, Name = "Archmage",
				Description = "Mage damage x5", Cost = 3000000,
				Effect = {Type = "HeroDamageMultiplier", Value = 5}},
			{Id = "AlchemicalFortune", Level = 150, Name = "Alchemical Fortune",
				Description = "Your gold earned x1.25", Cost = 300000000,
				Effect = {Type = "GoldMultiplier", Value = 1.25}},
			{Id = "LegendaryMage", Level = 200, Name = "Legendary Mage",
				Description = "Mage damage x10", Cost = 30000000000,
				Effect = {Type = "HeroDamageMultiplier", Value = 10}},
		},
	},
	Impact = {
		FlashColor = Color3.fromRGB(255, 245, 200),
		FlashDuration = 0.12,
	},
}
